
platform :ios, '8.0'

target 'LSTPopView_Example' do
  pod 'LSTPopView', :path => '../'
  pod 'LSTCategory'
  pod 'Masonry'
  pod 'Bugly'

  
  target 'LSTPopView_Tests' do
    inherit! :search_paths

    
  end
end
